main: com.linmalu.linkedchat.Main
name: LinmaluLinkedChat
version: 1.13.2.0
author: 린마루(Linmalu)
website: http://blog.linmalu.com/
description: LinmaluLinkedChat
depend: [LinmaluLibrary]

commands:
    LinmaluLinkedChat:
        description: 'LinmaluLinkedChat'
        aliases: [llc, 채팅]
        usage: '명령어 : /<command>'
